# don't forget to update config.model
environment: sit

app:
  name: inquiry

server:
  port: 8080
  timeout: 15
  
log:
  environment: production
  level: info
  format: json

postgres:
  db-name: pan-db
  host: 172.28.240.42
  port: 5432
  pool-size: 30

redis:
  address: 172.28.241.3:6379
  database: 1

user-list-key: ATP_USER_LIST

  




